"""Report generator — JSON + Markdown reports with SBOM, findings, gate decision."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_json_report(
    sbom_cdx: dict | None = None,
    sbom_spdx: dict | None = None,
    findings: list | None = None,
    license_checks: list | None = None,
    pqc_findings: list | None = None,
    fw_report: dict | None = None,
    gate_result: dict | None = None,
    policy_file: str = "",
) -> dict[str, Any]:
    """Generate structured JSON report."""
    report: dict[str, Any] = {
        "report": {
            "tool": "supplysec",
            "version": "1.0.0",
            "generated_at": _now_iso(),
            "policy_file": policy_file,
        },
        "sbom": {
            "cyclonedx": sbom_cdx,
            "spdx": sbom_spdx,
        },
        "advisory_findings": findings or [],
        "license_checks": license_checks or [],
        "pqc_findings": pqc_findings or [],
        "firmware_audit": fw_report or {},
        "gate": gate_result or {"passed": True, "exit_code": 0, "summary": "N/A"},
    }
    return report


def _md_finding_row(f: dict) -> str:
    sev = f.get("severity", f.get("advisory", {}).get("severity", "n/a"))
    cve = f.get("cve", f.get("advisory", {}).get("cve_id", "n/a"))
    pkg = f.get("package", f.get("advisory", {}).get("package", "n/a"))
    ver = f.get("version", f.get("affected_version", "n/a"))
    msg = f.get("message", "")
    return f"| {sev} | {cve} | {pkg} | {ver} | {msg} |"


def generate_markdown_report(
    report_data: dict,
    output_path: str | Path,
) -> Path:
    """Generate Markdown report from JSON report data."""
    gate = report_data.get("gate", {})
    findings = report_data.get("advisory_findings", [])
    lic_checks = report_data.get("license_checks", [])
    pqc = report_data.get("pqc_findings", [])
    fw = report_data.get("firmware_audit", {})
    sbom = report_data.get("sbom", {})
    meta = report_data.get("report", {})

    lines: list[str] = []
    lines.append("# SupplySec Security Gate Report")
    lines.append("")
    lines.append(f"**Generated:** {meta.get('generated_at', 'N/A')}")
    lines.append(f"**Policy:** {meta.get('policy_file', 'N/A')}")
    lines.append("")

    passed = gate.get("passed", True)
    exit_code = gate.get("exit_code", 0)
    summary = gate.get("summary", "N/A")
    status_icon = "PASS" if passed else "FAIL"
    lines.append(f"## Gate: {status_icon} (exit {exit_code})")
    lines.append(f"> {summary}")
    lines.append("")

    if findings:
        lines.append("## Advisory Findings")
        lines.append("| Severity | CVE | Package | Version | Message |")
        lines.append("|----------|-----|---------|---------|---------|")
        for f in findings:
            lines.append(_md_finding_row(f))
        lines.append("")

    if lic_checks:
        lines.append("## License Checks")
        lines.append("| Package | License | Allowed | Reason |")
        lines.append("|---------|---------|---------|--------|")
        for lc in lic_checks:
            allowed = "Yes" if lc.get("allowed", True) else "NO"
            lines.append(f"| {lc.get('package','')} | {lc.get('detected_license','')} | {allowed} | {lc.get('reason','')} |")
        lines.append("")

    if pqc:
        lines.append("## PQC Findings")
        lines.append("| Severity | Type | Key ID | Message |")
        lines.append("|----------|------|--------|---------|")
        for p in pqc:
            lines.append(f"| {p.get('severity','')} | {p.get('type','')} | {p.get('key_id','')} | {p.get('message','')} |")
        lines.append("")

    if fw and fw.get("findings"):
        lines.append("## Firmware Audit")
        lines.append(f"- File: {fw.get('filename','N/A')}")
        lines.append(f"- Size: {fw.get('size_bytes',0)} bytes")
        lines.append(f"- Entropy: {fw.get('entropy',0)}")
        for ff in fw["findings"]:
            lines.append(f"  - [{ff.get('severity','')}] {ff.get('message','')}")
        lines.append("")

    cdx = sbom.get("cyclonedx", {})
    components = cdx.get("components", []) if cdx else []
    if components:
        lines.append("## SBOM Summary")
        lines.append(f"Components: {len(components)}")
        lines.append(f"CycloneDX spec: {cdx.get('specVersion', 'N/A')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by supplysec 1.0.0 — offline, fixture-based.*")

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    return out


def write_report(
    output_dir: str | Path,
    **kwargs,
) -> dict[str, Path]:
    """Write JSON + Markdown reports to output_dir."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    report_data = generate_json_report(**kwargs)

    json_path = out / "report.json"
    json_path.write_text(json.dumps(report_data, indent=2, default=str))

    md_path = out / "report.md"
    generate_markdown_report(report_data, md_path)

    return {"json": json_path, "markdown": md_path}
